Restaurants/Controllers/DishController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Restaurants.Data;
using Restaurants.Models;

namespace Restaurants.Controllers
{
    public class DishController : Controller
    {
        private ApplicationDbContext _context;

        public DishController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dish/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dish/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dish dish)
        {
            try
            {
                Dish dd = _context.Dishes.FirstOrDefault(d => d.Id == dish.Id);
                if (ModelState.IsValid && dd == null)
                {
                    _context.Dishes.Add(dish);
                    _context.SaveChanges();

                    return RedirectToAction("Index", "Institution");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToBasket(int dishId, int instituteId)
        {
            try
            {
                ApplicationUser user = _context.Users.FirstOrDefault(u => u.Email == HttpContext.User.Identity.Name);
                Basket basket = _context.Baskets
                    .FirstOrDefault(d => d.DishId == dishId && d.InstitutionId == instituteId && d.UserId == user.Id);
                if (basket == null)
                {
                    _context.Baskets.Add(new Basket()
                    {
                        Dish = _context.Dishes.FirstOrDefault(d => d.Id == dishId),
                        User = user,
                        InstitutionId = instituteId,
                        DishCount = 1
                    });
                    _context.SaveChanges();
                }
                else
                {
                    basket.DishCount++;
                }
                _context.SaveChanges();
                return RedirectToAction("Details", "Institution", new {id = instituteId});
            }
            catch
            {
                return View();
            }
        }
    }
}

Restaurants/Views/Shared/_BasketPartial.cshtml
@model Restaurants.ViewModels.DetailsViewModel
<div class="col-12 col-md-3 col-xl-2 bd-sidebar">
    <h5>Корзина @User.Identity.Name</h5>
    <table class="table">
        <thead>
        <tr>
            <th>
                Dish
            </th>
            <th>
                Количество порций
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Baskets) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Dish.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DishCount)
                </td>
            </tr>
        }
        </tbody>
    </table>
    <div>Итого: @Model.Summ</div>
</div>

Restaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurants</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Restaurants</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Institution" asp-action="Index">Главная</a></li>
                    <li><a asp-area="" asp-controller="Institution" asp-action="Create">Добавить ресторан</a></li>
                    <li><a asp-area="" asp-controller="Dish" asp-action="Create">Добавить блюдо</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Restaurants</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>